apiVersion: v1
kind: ConfigMap
metadata:
  name: elastalert-config-json
data:
  config.json: |
    {
      "appName": "elastalert-server",
      "port": 3030,
      "wsport": 3333,
      "elastalertPath": "/opt/elastalert",
      "verbose": false,
      "es_debug": false,
      "debug": false,
      "rulesPath": {
        "relative": true,
        "path": "/rules"
      },
      "templatesPath": {
        "relative": true,
        "path": "/rule_templates"
      },
      "es_host": "elastic-elasticsearch-client",
      "es_port": 9200,
      "writeback_index": "elastalert_status"
    }
