apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastalert
  labels:
    app: elasticalert
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticalert
  template:
    metadata:
      labels:
        app: elasticalert
    spec:
      containers:
      - image: bitsensor/elastalert:2.0.0
        name: elastalert-container
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 300Mi
        volumeMounts:
        - mountPath: /opt/elastalert/config.yaml
          subPath: config.yaml
          name: conf-volume
        - mountPath: /opt/elastalert-server/config/
          name: conf23
        - mountPath: /opt/elastalert/rule_templates/
          name: rules-tmpl-volume
        - mountPath: /opt/elastalert/smtp.yaml
          subPath: smtp:yaml
          name: smtp-conf
      volumes:
      - name: conf-volume
        configMap:
          name: elastalert-config-yaml
      - name: conf23
        configMap:
          name: elastalert-server
          items:
          - key: config.json
            path: config.json
          - key: config-test.yaml
            path: config-test.yaml
      - name: rules-tmpl-volume
        configMap:
          name: elastalert-rule-templates
      - name: smtp-conf
        secret:
          secretName: elasticalert
