apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastalert
  labels:
    app: elasticalert
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticalert
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: elasticalert
    spec:
      containers:
      - image: bitsensor/elastalert:2.0.0
        name: elastalert-container
        ports:
        - containerPort: 3030
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 300Mi
        volumeMounts:
        - mountPath: /opt/elastalert/config.yaml
          subPath: config.yaml
          name: conf-volume
        - mountPath: /opt/elastalert-server/config/config.json
          subPath: config.json
          name: conf2
        - mountPath: /opt/elastalert-server/config/config-test.yaml
          subPath: config-test.yaml
          name: conf3
        - mountPath: /opt/elastalert/rule_templates/
          name: rules-tmpl-volume
        - mountPath: /opt/elastalert/smtp.yaml
          subPath: smtp:yaml
          name: smtp-conf
      volumes:
      - name: conf-volume
        configMap:
          name: elastalert-config-yaml
      - name: conf2
        configMap:
          name: elastalert-config-json
      - name: conf3
        configMap:
          name: elastalert-config-test
      - name: rules-tmpl-volume
        configMap:
          name: elastalert-rule-templates
      - name: smtp-conf
        secret:
          secretName: elasticalert
