# deployment.yaml
replicas: 1

strategy:
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 1

image: bitsensor/elastalert
tag: 2.0.0

port: 3030

resources:
  requests:
    cpu: 10m
    memory: 100Mi
  limits:
    cpu: 100m
    memory: 300Mi

# secrets.yaml
# smtp.yaml: data in base64
# name: "myusername"
# password: "mypassword"
data:
  smtp.yaml: dXNlcjogImFsZXJ0bWFuYWdlci5zbHVybSIKcGFzc3dvcmQ6ICJTbHVybTIwMjAiCg==
